modLoader="javafml"
loaderVersion="${forgeVersion}"
license="LGPL-3.0"
issueTrackerURL="https://github.com/plasmoapp/plasmo-voice/issues"
[[mods]]
modId="plasmovoice"
version="${version}"
displayName="Bridge Voice"
displayURL="https://github.com/plasmoapp/plasmo-voice"
logoFile="icon.png"
authors="ImD4rken"
description="Chat de priximidad para eventos de Bridge Productions"
[[dependencies.plasmovoice]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersion}"
    ordering="NONE"
    side="BOTH"
[[dependencies.plasmovoice]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersions}"
    ordering="NONE"
    side="BOTH"
